# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'practiceui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.practicestartButton = QtWidgets.QPushButton(self.centralwidget)
        self.practicestartButton.setObjectName("practicestartButton")
        self.horizontalLayout_2.addWidget(self.practicestartButton)
        self.practicewpmBox = QtWidgets.QComboBox(self.centralwidget)
        self.practicewpmBox.setObjectName("practicewpmBox")
        self.practicewpmBox.addItem("")
        self.horizontalLayout_2.addWidget(self.practicewpmBox)
        self.selectionBox = QtWidgets.QComboBox(self.centralwidget)
        self.selectionBox.setObjectName("selectionBox")
        self.selectionBox.addItem("")
        self.selectionBox.addItem("")
        self.selectionBox.addItem("")
        self.selectionBox.addItem("")
        self.horizontalLayout_2.addWidget(self.selectionBox)
        self.practicerepeatButton = QtWidgets.QPushButton(self.centralwidget)
        self.practicerepeatButton.setObjectName("practicerepeatButton")
        self.horizontalLayout_2.addWidget(self.practicerepeatButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.practiceEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.practiceEdit.setObjectName("practiceEdit")
        self.horizontalLayout_3.addWidget(self.practiceEdit)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rxBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.rxBrowser.setObjectName("rxBrowser")
        self.horizontalLayout.addWidget(self.rxBrowser)
        self.txBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.txBrowser.setObjectName("txBrowser")
        self.horizontalLayout.addWidget(self.txBrowser)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Morse Practice"))
        self.practicestartButton.setText(_translate("MainWindow", "Listen"))
        self.practicewpmBox.setItemText(0, _translate("MainWindow", "20 WPM"))
        self.selectionBox.setItemText(0, _translate("MainWindow", "Alphabet"))
        self.selectionBox.setItemText(1, _translate("MainWindow", "Codegroups"))
        self.selectionBox.setItemText(2, _translate("MainWindow", "Callsigns"))
        self.selectionBox.setItemText(3, _translate("MainWindow", "Words"))
        self.practicerepeatButton.setText(_translate("MainWindow", "Repeat"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
