# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simulatedui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(754, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.simulatedBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.simulatedBrowser.setObjectName("simulatedBrowser")
        self.gridLayout.addWidget(self.simulatedBrowser, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.showBox = QtWidgets.QCheckBox(self.centralwidget)
        self.showBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.showBox.setObjectName("showBox")
        self.horizontalLayout.addWidget(self.showBox)
        self.callsignButton = QtWidgets.QPushButton(self.centralwidget)
        self.callsignButton.setObjectName("callsignButton")
        self.horizontalLayout.addWidget(self.callsignButton)
        self.simulatedrepeatButton = QtWidgets.QPushButton(self.centralwidget)
        self.simulatedrepeatButton.setObjectName("simulatedrepeatButton")
        self.horizontalLayout.addWidget(self.simulatedrepeatButton)
        self.simulatedwpnCombo = QtWidgets.QComboBox(self.centralwidget)
        self.simulatedwpnCombo.setObjectName("simulatedwpnCombo")
        self.simulatedwpnCombo.addItem("")
        self.horizontalLayout.addWidget(self.simulatedwpnCombo)
        self.simulatedstartButton = QtWidgets.QPushButton(self.centralwidget)
        self.simulatedstartButton.setObjectName("simulatedstartButton")
        self.horizontalLayout.addWidget(self.simulatedstartButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.callsignLabel = QtWidgets.QLabel(self.centralwidget)
        self.callsignLabel.setObjectName("callsignLabel")
        self.horizontalLayout_3.addWidget(self.callsignLabel)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.simulatedEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.simulatedEdit.setObjectName("simulatedEdit")
        self.horizontalLayout_2.addWidget(self.simulatedEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 754, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simulated QSO"))
        self.showBox.setText(_translate("MainWindow", "Show"))
        self.callsignButton.setText(_translate("MainWindow", "Update Callsign"))
        self.simulatedrepeatButton.setText(_translate("MainWindow", "Repeat"))
        self.simulatedwpnCombo.setItemText(0, _translate("MainWindow", "20 WPM"))
        self.simulatedstartButton.setText(_translate("MainWindow", "Start"))
        self.label_2.setText(_translate("MainWindow", "My Callsign:"))
        self.callsignLabel.setText(_translate("MainWindow", "(My Callsign)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
